repos:
  - repo: local
    hooks:
      - id: lint-all
        name: Format & Lint
        entry: bash -c 'pnpm lint:all'
        language: system
        types_or: [javascript, jsx, ts, tsx, json, markdown, css]
        pass_filenames: false
